### ISSUE TITLE
geometry not saved after importing

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#347]
**Describe the bug**
trying to create a simulation for a file with an imported geometry went fine, but it wasn't saved in the resulting file. 

**To Reproduce**

 - load goldbeter.cps in copasi -> export as sbml
 - import exported sbml file, then improt geometry from model (choosing the brusselator example from earlier)
 - mark species as spatially resolved and add initial concentrations,
 - run
 - save model ...

**Expected behavior**
would be nice if the saved model would be complete. 

**Screenshots**

**Comment by lkeegan** [comment]
This bug is caused by writing the imported sampled field geometry back to the sbml document from which the geometry was imported, instead of the sbml document that contains the actual model.

To avoid similar future bugs, ideally all functions that import stuff from an SBML doc should take const refs to the input sbml document, i.e.:
  - importDimensions
  - importSampledFieldGeometry
  - importParametricGeometry
  - importGeometryFromAnalyticGeometry
  - ...
