### ISSUE TITLE
add support for dune membrane fluxes

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#380]
dune-copasi will soon support membrane fluxes:

https://gitlab.dune-project.org/copasi/dune-copasi/-/merge_requests/30

i.e. for all models that are currently supported we can remove the explicit rectangular membrane compartments and replace them with flux conditions on the membrane

todo:

- ~(temporarily)~ remove all rectangle-related stuff from meshing, GUI, ini files etc
- implement simulation of models with dune using membrane fluxes

note: the rectangle-related stuff ~will be required again later to implement~ should not be required to implement #265

**Comment by SoilRos** [comment]
> note: the rectangle-related stuff ~~will be required again later to implement~~ should not be required to implement #265

I would not remove the rectangle things completely: The PDE on the d-1 manifold is not so easy to implement in PDELab and I am not completely sure how the coupling between dimensions would look like in code. And even if I manage to do it and do not require the rectangles for extra species in the membrane, I am still not sure of the tradeoff of the two approximations for representing the membrane.

From the GUI point of view, I can imagine that to be a pain because you would have to know whether there will be extra variables on the membrane before meshing.

**Comment by lkeegan** [comment]
@SoilRos I think with the membrane flux conditions the d-1 manifold PDE would not be required on the dune side - see https://github.com/spatial-model-editor/spatial-model-editor/issues/265#issuecomment-717105202 and let me know what you think
