### ISSUE TITLE
Reset of a simulation adds new values for simulation length and image interval

### ISSUE THREAD

**Issue by SoilRos** [spatial-model-editor/spatial-model-editor#745]
**Describe the bug**
Some times when pressing the reset button in the simulation tab, the simulation length and the image interval fields get changed to a default value. Some other times, the values get repeated with a semicolon in between.

**To Reproduce**
* Open the `very-simple-model` from the examples.
* Run simulation until the end.
* Press reset button.

**Expected behavior**
No change in these options.

**Screenshots**

https://user-images.githubusercontent.com/6602798/161972937-549635fe-4b1b-4d4e-a589-c7f40f1188c0.mov

**Comment by lkeegan** [comment]
Thanks for the bug report, the simulation lengths are more complicated than they should be due to trying to support these different use cases:
- load a model with existing simulation results, "reset" & "simulate" should repeat the same simulation
- similarly, if you simulate a model for length x, then for y, then for z, "save" or "reset" should set the simulation length to `x;y;z` (so that "reset' and "simulate" reproduces same simulation as above)
- load a model with no simulation results, should have some default simulation time

I think the interaction between the last two of these cases is what is causing the extra `100;` to be pre-pended to the simulation lengths on "reset" in your example - will clean this up.

**Comment by SoilRos** [comment]
Thanks :)
