### ISSUE TITLE
Negative concentrations when using functions and PIXEL

### ISSUE THREAD

**Issue by formersbach** [spatial-model-editor/spatial-model-editor#855]
**Describe the bug**
When using functions to define reaction kinetics in combination with PIXEL solver negative concentrations can arise. Manually declaring the reaction kinetics resolves the negative concentration issue. Importing an identical model with functions defined from a SBML file does not reproduce the same behavior.

**To Reproduce**
- [Download the models.](https://heibox.uni-heidelberg.de/d/b0243b5d71cc4912a36a/)
- Load files into SME
- set simulation type to PIXEL
- Simulate and compare the three models

**Expected behavior**
As far as I can see all models _should_ behave identically. Negative values should not be possible and using functions to declare reaction kinetics vs manually declaring them shouldn't matter. Maybe I'm also missing something about how functions are intended to work though ^^

**Screenshots**
Negative values with declaration via functions:
![Selfmade negative](https://user-images.githubusercontent.com/49982367/222391716-3e06cd86-befb-4a4b-a035-ab95d01260ef.png)
Positive values with manual declaration:
![Selfmade positive](https://user-images.githubusercontent.com/49982367/222392189-bdfc2309-fecb-406b-8ca4-73af9c932230.png)
Positive values when importing from SBML with declaration via functions (model was run with different spatial distribution then img 2):
![COPASI positive](https://user-images.githubusercontent.com/49982367/222392370-03d63f2d-17ee-4c3b-8d17-0894a26abfc8.png)

**Comment by lkeegan** [comment]
@formersbach thanks for the bug report.

I agree all your models should behave identically, the bug appears to be caused by some function arguments having the same name as a species in the model, and it looks like the software is using that species concentration instead of the supplied argument when evaluating the functions - I'll investigate further and fix this.

In the meantime, a workaround is to change the function parameter names such that they don't overlap with any species names - I did this here and now the simulation results are non-negative:

[Selfmade_negative_renamed_function_parameters.zip](https://github.com/spatial-model-editor/spatial-model-editor/files/10870504/Selfmade_negative_renamed_function_parameters.zip)

**Comment by formersbach** [comment]
@lkeegan Thanks for the quick response!
If it helps I added another model to the [folder](https://heibox.uni-heidelberg.de/d/b0243b5d71cc4912a36a/) which is where I  originally identified this behavior. Here the only overlapping arguments in naming are the reaction constant, species are named differently than the function arguments. 
Thanks for the workaround!
