### ISSUE TITLE
Dune simulation is too slow

### ISSUE THREAD

**Issue by SoilRos** [spatial-model-editor/spatial-model-editor#957]
**Is your feature request related to a problem? Please describe.**
When compared to the base command line program (`dune-copasi`), the one provided by the spatial model simulator is significantly slower.

As an example the circadian-clock example takes 4:30 minutes to reach 40 hours of simulation. In turn, the command line takes 6.8 seconds to finish the same 40 hours of the same simulation. One part of this seems to be that multi-threading is not happening in the editor, but there is also something else going on because it is about one order of magnitude slower even when scaling by the actual cores/minute used to solve the problem (my system has 10 cores).

**Describe the solution you'd like**
A dune simulator that has similar performance to the one produced by the base `dune-copasi` program.

**Comment by lkeegan** [comment]
Thanks for reporting - I'll look into this.

**Comment by lkeegan** [comment]
@SoilRos I couldn't reproduce this - would you be able to try this comparison again with the latest [macOS arm preview binary](https://github.com/ssciwr/sme-osx-arm64/releases/download/latest/spatial-model-editor.dmg) to see if this issue is still present with the latest changes?

I tried the GUI vs dune-copasi on my linux desktop and they both ran in (roughly) 5s (and both used multithreading)

I also tried the GUI on an M2 Mac and it ran in a similar time and used multi-threading:

https://github.com/spatial-model-editor/spatial-model-editor/assets/12845624/dc9e2301-07ee-4e66-b18c-1bc246807634

**Comment by SoilRos** [comment]
Ahh yes, my bad! I did click in the released version 1.5 without realizing. The pre-release works very nice and fast! Sorry for the noice :-)

**Comment by lkeegan** [comment]
Great, thanks for checking! (I test it on the same mac used to build it, so good to have confirmation it also works on a different machine)
